// @flow

const ADD_ITEM = "ADD_ITEM";
const REMOVE_ITEM = "REMOVE_ITEM";
const ADD_ABILITY = "ADD_ABILITY";
const REMOVE_ABILITY = "REMOVE_ABILITY";
const NEW_CHARACTER = "NEW_CHARACTER";
const FETCH_CHARACTER = "FETCH_CHARACTER";
const SAVE_CHARACTER = "SAVE_CHARACTER";
const UPDATE_CHARACTER = "UPDATE_CHARACTER";
const DELETE_CHARACTER = "DELETE_CHARACTER";
const CHANGE_CHARACTER_FORM = "CHANGE_CHARACTER_FORM";
const CHANGE_CHARACTER_FORM_NESTED_LISTS = "CHANGE_CHARACTER_FORM_NESTED_LISTS";

export {
  FETCH_CHARACTER,
  SAVE_CHARACTER,
  UPDATE_CHARACTER,
  DELETE_CHARACTER,
  CHANGE_CHARACTER_FORM,
  CHANGE_CHARACTER_FORM_NESTED_LISTS,
  NEW_CHARACTER,
  ADD_ITEM,
  REMOVE_ITEM,
  ADD_ABILITY,
  REMOVE_ABILITY
};
