// @flow

const NEW_GAME = "NEW_GAME";
const FETCH_GAME = "FETCH_GAME";
const SAVE_GAME = "SAVE_GAME";
const UPDATE_GAME = "UPDATE_GAME";
const DELETE_GAME = "DELETE_GAME";
const CHANGE_GAME_FORM = "CHANGE_GAME_FORM";

export {
  FETCH_GAME,
  SAVE_GAME,
  UPDATE_GAME,
  DELETE_GAME,
  CHANGE_GAME_FORM,
  NEW_GAME
};
