// @flow

const FETCH_DASHBOARD_DATA = "FETCH_DASHBOARD_DATA";
const FETCH_DASHBOARD_DATA_PENDING = `${FETCH_DASHBOARD_DATA}_PENDING`;
const FETCH_DASHBOARD_DATA_SUCCESS = `${FETCH_DASHBOARD_DATA}_SUCCESS`;
const FETCH_DASHBOARD_DATA_FAILURE = `${FETCH_DASHBOARD_DATA}_FAILURE`;

export {
  FETCH_DASHBOARD_DATA,
  FETCH_DASHBOARD_DATA_PENDING,
  FETCH_DASHBOARD_DATA_SUCCESS,
  FETCH_DASHBOARD_DATA_FAILURE
};
